name: Dhruv Auto Scanner

on:
  schedule:
    - cron: "*/15 3-9 * * 1-5"   # Every 15 minutes, Monâ€“Fri, 9:15 AM to 3:00 PM IST
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install all required dependencies
      - name: Install dependencies
        run: |
          pip install logzero
          pip install SmartApi-python
          pip install pyotp
          pip install requests
          pip install pandas
          pip install websocket-client

      # Run Scanner
      - name: Run scanner
        run: python3 telegram_scanner.py
